name: lz - oases-HeyAzure-prod

on:
  workflow_dispatch:

  pull_request_target:
    types:
      - closed
    paths:
      - "landing-zones/oases-prod/oases-HeyAzure-prod.bicepparam"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  landingzone:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: ./.github/workflows/template-landing-zones.yml
    with:
      managementGroupScope: "oases"
      managementGroupHierarchy: "prod"
      parameterFile: ./landing-zones/oases-prod/oases-HeyAzure-prod.bicepparam
    secrets: inherit
