name: platform - policy

on:
  push:
    branches-ignore:
      - main
    paths:
        - 'policy/**'
        - '.github/workflows/template-policy.yml'
        - '.github/workflows/platform-policy.yml'

  pull_request_target:
    types:
      - closed
    paths:
      - 'policy/**'

  workflow_dispatch:
    inputs:
      managementGroupHierarchy:
        description: 'Management Group Hierarchy'
        required: true
        default: 'test'
        type: choice
        options:
          - 'test'
          - 'prod'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.managementGroupHierarchy == 'test') ||  
        github.ref != 'refs/heads/main'        
    uses: ./.github/workflows/template-policy.yml
    with:
      managementGroupHierarchy:  ${{ github.event.inputs.managementGroupHierarchy || 'test' }}
    secrets: inherit

  prod:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.managementGroupHierarchy == 'prod') ||
        github.event.pull_request.merged == true 
    uses: ./.github/workflows/template-policy.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy || 'prod' }}
    secrets: inherit