name: template - monitor

on:
  workflow_call:
    inputs:
        managementGroupHierarchy:
          required: true
          type: string

env:
  ManagementGroupId: ${{ vars.TOP_LEVEL_MANAGEMENT_GROUP_NAME }}
  Location: ${{ vars.AZURE_DEFAULT_LOCATION }}
  DenySettingsMode: 'None'
  ActionOnUnmanage: 'deleteAll'
  GitHubOrganizationName: ${{ github.repository_owner }}
  GitHubRepositoryName: ${{ github.event.repository.name }}
  environment: ${{ inputs.managementGroupHierarchy }}
  DenySettingsApplyToChildScopes: 'false'
jobs:
    AzureResources:
        runs-on: ${{ vars.RUNNER_IMAGE_VERSION }}
        environment: ${{ inputs.managementGroupHierarchy }}
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: get github token
          id: github-token
          uses: actions/create-github-app-token@v1
          with:
            app-id: ${{ vars.APP_GITHUB_AZUREPLATFORM_ID }}
            private-key: ${{ secrets.APP_GITHUB_AZUREPLATFORM_KEY }}
            owner: ${{ github.repository_owner }}
            
        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: true

        - name: Azure resources
          uses: azure/powershell@v2
          env:
            GH_TOKEN: ${{ steps.github-token.outputs.token }}
          with:
            azPSVersion: 'latest'
            inlineScript: |
              . ./.github/utils/new-deployment.ps1              

              $params = @{
                Name                     = 'monitor'
                templateFile             = './monitor/bicep/main.bicep'
                environment              = '${{ inputs.managementGroupHierarchy }}'
                subscriptionId           = '${{ vars.PLALTFORM_SUBSCRIPTION_ID }}'
                engineerEmail            = '${{ vars.AZURE_PLATFORM_ENGINEER_EMAIL }}'
              }
              New-platformDeployment @params