name: template - identity

on:
  workflow_call:
    inputs:
        managementGroupHierarchy:
          required: true
          type: string

env:
  ManagementGroupId: ${{ vars.TOP_LEVEL_MANAGEMENT_GROUP_NAME }}
  Location: ${{ vars.AZURE_DEFAULT_LOCATION }}
  DenySettingsMode: 'None'
  ActionOnUnmanage: 'deleteAll'
  GitHubOrganizationName: ${{ github.repository_owner }}
  GitHubRepositoryName: ${{ github.event.repository.name }}
  environment: ${{ inputs.managementGroupHierarchy }}
  DenySettingsApplyToChildScopes: 'false'
jobs:
    roleAssignments:
      runs-on: ${{ vars.RUNNER_IMAGE_VERSION }}
      environment: ${{ inputs.managementGroupHierarchy }}
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID}}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: access control
        uses: azure/powershell@v2
        env:
          GH_TOKEN: ${{ steps.github-token.outputs.token }}
        with:
          azPSVersion: 'latest'
          inlineScript: |
            . ./.github/utils/new-deployment.ps1

            $params = @{
              Name                        = 'identity-accessControl'
              templateFile                = './identity/bicep/main.bicep'
              TemplateParameterFile       = './identity/parameters/main-${{ inputs.managementGroupHierarchy }}.bicepparam'
              gazelleAdminGroupId         = '${{ vars.AZURE_PLATFORM_ADMIN_GROUP_ID }}'
              topLevelManagementGroupName = '${{ vars.TOP_LEVEL_MANAGEMENT_GROUP_NAME }}'
              environment                 = '${{ inputs.managementGroupHierarchy }}'
            }
            New-platformDeployment @params
