name: template - Management Groups

on:
  workflow_call:
    inputs:
      managementGroupHierarchy:
        required: true
        type: string

jobs:
  hierarchy:
    runs-on: ${{ vars.RUNNER_IMAGE_VERSION }}
    environment: ${{ inputs.managementGroupHierarchy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: validate branch and environment
        run: |
          if [[ "${GITHUB_REF##*/}" != "main" && "${{ inputs.managementGroupHierarchy }}" == "prod" ]]; then
            echo "ERROR: You cannot run on prod environment from a non-main branch."
            exit 1
          fi

      - name: get github token
        id: github-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_GITHUB_AZUREPLATFORM_ID }}
          private-key: ${{ secrets.APP_GITHUB_AZUREPLATFORM_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID}}
          allow-no-subscriptions: true

      - name: management group hierarchy
        env:
          GITHUB_TOKEN: ${{ steps.github-token.outputs.token }}
          GITHUB_ORGANIZATION_NAME: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          ENVIRONMENT: ${{ inputs.managementGroupHierarchy }}
          TOP_LEVEL_MANAGEMENT_GROUP_ID: /providers/Microsoft.Management/managementGroups/${{ vars.TOP_LEVEL_MANAGEMENT_GROUP_NAME }}
        shell: pwsh
        run: |
          . ./.github/utils/set-githubVariables.ps1
          . ./.github/utils/write-stackSummary.ps1

          $deployment = az stack mg create `
              --name 'managementGroups' `
              --location ${{ vars.AZURE_DEFAULT_LOCATION }} `
              --template-file './platform-management/management-groups/bicep/managementGroups.bicep' `
              --management-group-id ${{ vars.TOP_LEVEL_MANAGEMENT_GROUP_NAME }} `
              --deny-settings-mode 'None' `
              --action-on-unmanage 'deleteAll' `
              --deny-settings-apply-to-child-scopes `
              --parameters `
                  topLevelManagementGroupName=${{ env.TOP_LEVEL_MANAGEMENT_GROUP_ID }} `
                  environment=${{ inputs.managementGroupHierarchy }}

          Write-DeploymentStackSummary -StackJson $deployment

          $dynamicVar = ($deployment | ConvertFrom-Json).outputs

          Set-GitHubEnvironmentVariables $dynamicVar.GitHubEnvironmentVariables.Value.PSObject.Properties
          Set-GitHubRepositoryVariables $dynamicVar.GitHubRepositoryVariables.Value.PSObject.Properties
          Set-GitHubActionsVariables $dynamicVar.GitHubActionsVariables.Value.PSObject.Properties
